---
# copy cgi-bin scripts to run keystone under apache
  - name: create directory /usr/lib/cgi-bin/keystone
    file: path=/usr/lib/cgi-bin/keystone state=directory mode=0755
  - name: copy cgi-bin script to /usr/lib/cgi-bin/keystone directory
    copy: src=roles/common/files/keystone-cgi.py dest=/usr/lib/cgi-bin/keystone/admin owner=keystone group=keystone mode=0755

  - name: copy cgi-bin script to /usr/lib/cgi-bin/keystone directory
    copy: src=roles/common/files/keystone-cgi.py dest=/usr/lib/cgi-bin/keystone/main owner=keystone group=keystone mode=0755

# define ports 35357 and 5000 for keystone
  - name: add open ports for keystone
    copy: src=roles/common/files/ports.conf dest=/etc/apache2/ports.conf backup=yes

# create and enable virtual hosts for kestone workers
  - include_vars: main.yml
  - set_fact: items={{main_settings}}
  - name: site-avaliable-main
    template:  src=roles/common/temlates/05-keystone_wsgi.conf.j2 dest=/etc/apache2/sites-available/05-keystone_wsgi_main.conf backup=yes owner=keystone group=keystone mode=0755
  - set_fact: items={{admin_settings}}
  - name: site-avaliable-admin
    template:  src=roles/common/temlates/05-keystone_wsgi.conf.j2 dest=/etc/apache2/sites-available/05-keystone_wsgi_admin.conf backup=yes owner=keystone group=keystone mode=0755
  - name: stop keystone
    service: name=keystone state=stopped enabled=no
  - name: enable  keystone-admin
    command: a2ensite 05-keystone_wsgi_admin.conf
  - name: enable  keystone-main
    command: a2ensite 05-keystone_wsgi_main.conf
  - name: reload apache
    service: name=apache2 state=reloaded
# install needed packages
  - name: check if apache is installed
    command: dpkg-query -l apache2
    register: is_installed

  - name: install apache
    apt: name=apache2 state=present
    when: is_installed.rc==1

  - name: check if libapache2-mod-wsgi is  installed
    command: dpkg-query -l libapache2-mod-wsgi
    register: is_installed
  - name: install libapache2-mod-wsgi
    apt: name=libapache2-mod-wsgi state=present
    when: is_installed.rc==1
